title: "[WIP]PHP Laravel x React ！！ LINEで動く会員証ライブコーディング vol.1"
summary: "イベント「PHP Laravel x React ！！ LINEで動く会員証ライブコーディング vol.1」の資料です。https://linedevelopercommunity.connpass.com/event/250999/"
topics: ["php", "laravel", "react", "typescript", "line"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - preparing
  - keywords
  - system
  - laravel-echo-bot
  - laravel-members-card
  - liff-react
  - rich-menu
  - deploy

