title: "画像分析AIを使ったLINE Botを1時間で作ってみよう（顔認証編）～プロトアウト体験会～"
summary: "画像分析AIであるAzure Face API を組み合わせた LINE Bot を作成し、LINE Bot + Azure Face API 開発の一連の流れを実際に体験いただきます。"
topics: ["ハンズオン", "nodejs", "JavaScript", "LINE", "Azure"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter1
  - chapter2
  - chapter3
  - chapter4
